import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import "@radix-ui/themes/styles.css";
import SideNav from "./components/layout/SideNav.tsx/SideNav";
import Topbar from "./components/layout/Topbar.tsx/Topbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Swarm-Intelligence",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="content-wrapper">
          <SideNav></SideNav>
          <div className="main-layout">
            <Topbar />
            <main className="main-content">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
